import logging
import time
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError

from models import OptimizationRequest, OptimizationResponse, DirectiveInterpretation, HourlyPlan, StructuredAdjustment

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="GridWise API Shell")

@app.middleware("http")
async def latency_logging_middleware(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    # Secure logging: only logs method, path, and time. No payload or keys.
    logger.info(f"{request.method} {request.url.path} completed in {process_time:.4f}s")
    return response

@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    # Strict Secure Error Handling: Clean 400
    return JSONResponse(
        status_code=400,
        content={"detail": "Validation error", "errors": exc.errors()},
    )

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    # Strict Secure Error Handling: Safe 500 without leaking stack traces or secrets
    logger.error("An internal error occurred during request processing.", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal Server Error"}
    )

async def run_core_optimization(request: OptimizationRequest) -> OptimizationResponse:
    # TEAMMEMBER_1_WILL_REPLACE_THE_LOGIC_INSIDE_THIS_FUNCTION
    
    # Create mock interpretations
    interpretations = []
    for i, _ in enumerate(request.operator_notes):
        interpretations.append(
            DirectiveInterpretation(
                note_index=i,
                applies=False,
                directive_type="no_op",
                structured_adjustment=None,
                explanation="Mock interpretation for testing."
            )
        )
        
    # Create mock hourly plan
    hourly_plan = []
    for h in range(24):
        hourly_plan.append(
            HourlyPlan(
                hour=h,
                grid_kwh=10.0,
                solar_used_kwh=5.0,
                battery_action="idle",
                battery_kwh=0.0,
                battery_energy_after_kwh=request.battery.initial
            )
        )
        
    response = OptimizationResponse(
        scenario_id=request.scenario_id,
        directive_interpretation=interpretations,
        hourly_plan=hourly_plan,
        total_grid_kwh=240.0,
        total_cost_bdt=1200.0,
        peak_grid_kwh=10.0,
        plan_summary="This is a mock optimization plan generated by the API shell."
    )
    
    return response

@app.post("/optimize-energy", response_model=OptimizationResponse)
async def optimize_energy_endpoint(request: OptimizationRequest):
    return await run_core_optimization(request)
