import logging
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError

from models import OptimizationRequest, OptimizationResponse, DirectiveInterpretation, HourlyPlan, StructuredAdjustment

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="GridWise API Shell")

@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=400,
        content={"detail": "Validation error", "errors": exc.errors()},
    )

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Internal server error: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "An internal server error occurred."}
    )

@app.post("/optimize-energy", response_model=OptimizationResponse)
def optimize_energy_endpoint(request: OptimizationRequest):
    # Dummy Stub / Mock Logic
    
    # Create mock interpretations
    interpretations = []
    for i, _ in enumerate(request.operator_notes):
        interpretations.append(
            DirectiveInterpretation(
                note_index=i,
                applies=False,
                directive_type="no_op",
                structured_adjustment=None,
                explanation="Mock interpretation for testing."
            )
        )
        
    # Create mock hourly plan
    hourly_plan = []
    for h in range(24):
        hourly_plan.append(
            HourlyPlan(
                hour=h,
                grid_kwh=10.0,
                solar_used_kwh=5.0,
                battery_action="idle",
                battery_kwh=0.0,
                battery_energy_after_kwh=request.battery.initial
            )
        )
        
    response = OptimizationResponse(
        scenario_id=request.scenario_id,
        directive_interpretation=interpretations,
        hourly_plan=hourly_plan,
        total_grid_kwh=240.0,
        total_cost_bdt=1200.0,
        peak_grid_kwh=10.0,
        plan_summary="This is a mock optimization plan generated by the API shell."
    )
    
    return response
